server.port=8080
spring.application.name=tripmind
spring.data.mongodb.uri=mongodb://localhost:27017/tripmind
spring.data.redis.host=localhost
spring.data.redis.port=6379
app.jwt.secret=tripmind_super_secret_key_must_be_32_chars_min
app.jwt.expiration=86400000
openrouter.api.key=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
spring.thymeleaf.check-template-location=false